### PR TITLE
QoS Settings & NodeOptions

### LINKED ISSUE #10: Feat QoS

### PR DESCRIPTION
**Pull request by Philipp66904**
Same as here: https://github.com/THI-Drone/common_package/pull/12

### CODE REVIEW

**Comment by Philipp66904** [comment]
Unfortunately, it doesn't seem to work when used with the qr_code_scanner_node.

It complains about not finding `NodeOptions` in `rclpy.node`.

**Comment by J0hn-Lawrence** [comment]
Is this a potential blocker if it stays unsolved? I would think it does not make sense to only have the QoS in the cpp nodes (in case this does not work out)

**Comment by Philipp66904** [comment]
@J0las said that it seems like NodeOptions don't exist in the Python version as they do in C++.
Maybe there are other ways to set the QoS, but yes, this is a blocker.

**Comment by J0hn-Lawrence** [comment]
> @J0las said that it seems like NodeOptions don't exist in the Python version as they do in C++. Maybe there are other ways to set the QoS, but yes, this is a blocker.

@Finndows @maf0115 you guys should also be made aware of this. Please see if you can help out on this topic.

**Comment by Philipp66904** [comment]
According to @J0las and @di-math, setting the QoS in the subscriber is enough. Therefore, we can close this PR.

**Pull request closed without merging**
